# Generated by Django 4.2.9 on 2024-04-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='paid_status',
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_status',
            field=models.BooleanField(default=False, verbose_name='Payment status'),
        ),
    ]
